<a href="https://colab.research.google.com/github/tabaraksabbah1806a-glitch/Drug-Sensitivity-Prediction-in-Cancer-Cells/blob/main/Alzheimer_Early_Detection_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Libraries for data analysis
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine learning
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

Early Detection of Alzheimer’s Disease Using Blood-Based Gene Expression Data

Dataset: GEO (GSE63060)
Student: Tabarak Sabah Shaalan

In [2]:
!pip install GEOparse

Collecting GEOparse
  Downloading GEOparse-2.0.4-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: numpy>=1.7 in /usr/local/lib/python3.12/dist-packages (from GEOparse) (2.0.2)
Requirement already satisfied: pandas>=0.17 in /usr/local/lib/python3.12/dist-packages (from GEOparse) (2.2.2)
Requirement already satisfied: requests>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from GEOparse) (2.32.4)
Requirement already satisfied: tqdm>=4.31.1 in /usr/local/lib/python3.12/dist-packages (from GEOparse) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.17->GEOparse) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.17->GEOparse) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.17->GEOparse) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.21.0->GEOparse) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.21.0->GEOparse) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.21.0->GEOparse) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.21.0->GEOparse) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.17->GEOparse) (1.17.0)
Downloading GEOparse-2.0.4-py3-none-any.whl (29 kB)
Installing collected packages: GEOparse
Successfully installed GEOparse-2.0.4

In [3]:
import GEOparse

gse = GEOparse.get_GEO("GSE63060", destdir="./")

30-Mar-2026 18:52:01 DEBUG utils - Directory ./ already exists. Skipping.
DEBUG:GEOparse:Directory ./ already exists. Skipping.
30-Mar-2026 18:52:01 INFO GEOparse - Downloading ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE63nnn/GSE63060/soft/GSE63060_family.soft.gz to ./GSE63060_family.soft.gz
INFO:GEOparse:Downloading ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE63nnn/GSE63060/soft/GSE63060_family.soft.gz to ./GSE63060_family.soft.gz
100%|██████████| 120M/120M [00:00<00:00, 211MB/s]
30-Mar-2026 18:52:02 DEBUG downloader - Size validation passed
DEBUG:GEOparse:Size validation passed
30-Mar-2026 18:52:02 DEBUG downloader - Moving /tmp/tmpzy15jiyf to /content/GSE63060_family.soft.gz
DEBUG:GEOparse:Moving /tmp/tmpzy15jiyf to /content/GSE63060_family.soft.gz
30-Mar-2026 18:52:02 DEBUG downloader - Successfully downloaded ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE63nnn/GSE63060/soft/GSE63060_family.soft.gz
DEBUG:GEOparse:Successfully downloaded ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE63nnn/GSE63060/soft/GSE63060_family.soft.gz
30-Mar-2026 18:52:02 INFO GEOparse - Parsing ./GSE63060_family.soft.gz:
INFO:GEOparse:Parsing ./GSE63060_family.soft.gz:
30-Mar-2026 18:52:02 DEBUG GEOparse - DATABASE: GeoMiame
DEBUG:GEOparse:DATABASE: GeoMiame
30-Mar-2026 18:52:02 DEBUG GEOparse - SERIES: GSE63060
DEBUG:GEOparse:SERIES: GSE63060
30-Mar-2026 18:52:02 DEBUG GEOparse - PLATFORM: GPL6947
DEBUG:GEOparse:PLATFORM: GPL6947
30-Mar-2026 18:52:04 DEBUG GEOparse - SAMPLE: GSM1539080
DEBUG:GEOparse:SAMPLE: GSM1539080
30-Mar-2026 18:52:04 DEBUG GEOparse - SAMPLE: GSM1539081
DEBUG:GEOparse:SAMPLE: GSM1539081
30-Mar-2026 18:52:04 DEBUG GEOparse - SAMPLE: GSM1539082
DEBUG:GEOparse:SAMPLE: GSM1539082
30-Mar-2026 18:52:04 DEBUG GEOparse - SAMPLE: GSM1539083
DEBUG:GEOparse:SAMPLE: GSM1539083
30-Mar-2026 18:52:04 DEBUG GEOparse - SAMPLE: GSM1539084
DEBUG:GEOparse:SAMPLE: GSM1539084
30-Mar-2026 18:52:04 DEBUG GEOparse - SAMPLE: GSM1539085
DEBUG:GEOparse:SAMPLE: GSM1539085
30-Mar-2026 18:52:04 DEBUG GEOparse - SAMPLE: GSM1539086
DEBUG:GEOparse:SAMPLE: GSM1539086
30-Mar-2026 18:52:04 DEBUG GEOparse - SAMPLE: GSM1539087
DEBUG:GEOparse:SAMPLE: GSM1539087
30-Mar-2026 18:52:04 DEBUG GEOparse - SAMPLE: GSM1539088
DEBUG:GEOparse:SAMPLE: GSM1539088
30-Mar-2026 18:52:04 DEBUG GEOparse - SAMPLE: GSM1539089
DEBUG:GEOparse:SAMPLE: GSM1539089
30-Mar-2026 18:52:05 DEBUG GEOparse - SAMPLE: GSM1539090
DEBUG:GEOparse:SAMPLE: GSM1539090
30-Mar-2026 18:52:05 DEBUG GEOparse - SAMPLE: GSM1539091
DEBUG:GEOparse:SAMPLE: GSM1539091
30-Mar-2026 18:52:05 DEBUG GEOparse - SAMPLE: GSM1539092
DEBUG:GEOparse:SAMPLE: GSM1539092
30-Mar-2026 18:52:05 DEBUG GEOparse - SAMPLE: GSM1539093
DEBUG:GEOparse:SAMPLE: GSM1539093
30-Mar-2026 18:52:05 DEBUG GEOparse - SAMPLE: GSM1539094
DEBUG:GEOparse:SAMPLE: GSM1539094
30-Mar-2026 18:52:05 DEBUG GEOparse - SAMPLE: GSM1539095
DEBUG:GEOparse:SAMPLE: GSM1539095
30-Mar-2026 18:52:05 DEBUG GEOparse - SAMPLE: GSM1539096
DEBUG:GEOparse:SAMPLE: GSM1539096
30-Mar-2026 18:52:05 DEBUG GEOparse - SAMPLE: GSM1539097
DEBUG:GEOparse:SAMPLE: GSM1539097
30-Mar-2026 18:52:05 DEBUG GEOparse - SAMPLE: GSM1539098
DEBUG:GEOparse:SAMPLE: GSM1539098
30-Mar-2026 18:52:05 DEBUG GEOparse - SAMPLE: GSM1539099
DEBUG:GEOparse:SAMPLE: GSM1539099
30-Mar-2026 18:52:05 DEBUG GEOparse - SAMPLE: GSM1539100
DEBUG:GEOparse:SAMPLE: GSM1539100
30-Mar-2026 18:52:05 DEBUG GEOparse - SAMPLE: GSM1539101
DEBUG:GEOparse:SAMPLE: GSM1539101
30-Mar-2026 18:52:05 DEBUG GEOparse - SAMPLE: GSM1539102
DEBUG:GEOparse:SAMPLE: GSM1539102
30-Mar-2026 18:52:06 DEBUG GEOparse - SAMPLE: GSM1539103
DEBUG:GEOparse:SAMPLE: GSM1539103
30-Mar-2026 18:52:06 DEBUG GEOparse - SAMPLE: GSM1539104
DEBUG:GEOparse:SAMPLE: GSM1539104
30-Mar-2026 18:52:06 DEBUG GEOparse - SAMPLE: GSM1539105
DEBUG:GEOparse:SAMPLE: GSM1539105
30-Mar-2026 18:52:06 DEBUG GEOparse - SAMPLE: GSM1539106
DEBUG:GEOparse:SAMPLE: GSM1539106
30-Mar-2026 18:52:06 DEBUG GEOparse - SAMPLE: GSM1539107
DEBUG:GEOparse:SAMPLE: GSM1539107
30-Mar-2026 18:52:06 DEBUG GEOparse - SAMPLE: GSM1539108
DEBUG:GEOparse:SAMPLE: GSM1539108
30-Mar-2026 18:52:06 DEBUG GEOparse - SAMPLE: GSM1539109
DEBUG:GEOparse:SAMPLE: GSM1539109
30-Mar-2026 18:52:07 DEBUG GEOparse - SAMPLE: GSM1539110
DEBUG:GEOparse:SAMPLE: GSM1539110
30-Mar-2026 18:52:07 DEBUG GEOparse - SAMPLE: GSM1539111
DEBUG:GEOparse:SAMPLE: GSM1539111
30-Mar-2026 18:52:07 DEBUG GEOparse - SAMPLE: GSM1539112
DEBUG:GEOparse:SAMPLE: GSM1539112
30-Mar-2026 18:52:07 DEBUG GEOparse - SAMPLE: GSM1539113
DEBUG:GEOparse:SAMPLE: GSM1539113
30-Mar-2026 18:52:07 DEBUG GEOparse - SAMPLE: GSM1539114
DEBUG:GEOparse:SAMPLE: GSM1539114
30-Mar-2026 18:52:07 DEBUG GEOparse - SAMPLE: GSM1539115
DEBUG:GEOparse:SAMPLE: GSM1539115
30-Mar-2026 18:52:07 DEBUG GEOparse - SAMPLE: GSM1539116
DEBUG:GEOparse:SAMPLE: GSM1539116
30-Mar-2026 18:52:08 DEBUG GEOparse - SAMPLE: GSM1539117
DEBUG:GEOparse:SAMPLE: GSM1539117
30-Mar-2026 18:52:08 DEBUG GEOparse - SAMPLE: GSM1539118
DEBUG:GEOparse:SAMPLE: GSM1539118
30-Mar-2026 18:52:08 DEBUG GEOparse - SAMPLE: GSM1539119
DEBUG:GEOparse:SAMPLE: GSM1539119
30-Mar-2026 18:52:08 DEBUG GEOparse - SAMPLE: GSM1539120
DEBUG:GEOparse:SAMPLE: GSM1539120
30-Mar-2026 18:52:08 DEBUG GEOparse - SAMPLE: GSM1539121
DEBUG:GEOparse:SAMPLE: GSM1539121
30-Mar-2026 18:52:08 DEBUG GEOparse - SAMPLE: GSM1539122
DEBUG:GEOparse:SAMPLE: GSM1539122
30-Mar-2026 18:52:08 DEBUG GEOparse - SAMPLE: GSM1539123
DEBUG:GEOparse:SAMPLE: GSM1539123
30-Mar-2026 18:52:08 DEBUG GEOparse - SAMPLE: GSM1539124
DEBUG:GEOparse:SAMPLE: GSM1539124
30-Mar-2026 18:52:09 DEBUG GEOparse - SAMPLE: GSM1539125
DEBUG:GEOparse:SAMPLE: GSM1539125
30-Mar-2026 18:52:09 DEBUG GEOparse - SAMPLE: GSM1539126
DEBUG:GEOparse:SAMPLE: GSM1539126
30-Mar-2026 18:52:09 DEBUG GEOparse - SAMPLE: GSM1539127
DEBUG:GEOparse:SAMPLE: GSM1539127
30-Mar-2026 18:52:09 DEBUG GEOparse - SAMPLE: GSM1539128
DEBUG:GEOparse:SAMPLE: GSM1539128
30-Mar-2026 18:52:09 DEBUG GEOparse - SAMPLE: GSM1539129
DEBUG:GEOparse:SAMPLE: GSM1539129
30-Mar-2026 18:52:09 DEBUG GEOparse - SAMPLE: GSM1539130
DEBUG:GEOparse:SAMPLE: GSM1539130
30-Mar-2026 18:52:09 DEBUG GEOparse - SAMPLE: GSM1539131
DEBUG:GEOparse:SAMPLE: GSM1539131
30-Mar-2026 18:52:09 DEBUG GEOparse - SAMPLE: GSM1539132
DEBUG:GEOparse:SAMPLE: GSM1539132
30-Mar-2026 18:52:09 DEBUG GEOparse - SAMPLE: GSM1539133
DEBUG:GEOparse:SAMPLE: GSM1539133
30-Mar-2026 18:52:09 DEBUG GEOparse - SAMPLE: GSM1539134
DEBUG:GEOparse:SAMPLE: GSM1539134
30-Mar-2026 18:52:09 DEBUG GEOparse - SAMPLE: GSM1539135
DEBUG:GEOparse:SAMPLE: GSM1539135
30-Mar-2026 18:52:09 DEBUG GEOparse - SAMPLE: GSM1539136
DEBUG:GEOparse:SAMPLE: GSM1539136
30-Mar-2026 18:52:09 DEBUG GEOparse - SAMPLE: GSM1539137
DEBUG:GEOparse:SAMPLE: GSM1539137
30-Mar-2026 18:52:10 DEBUG GEOparse - SAMPLE: GSM1539138
DEBUG:GEOparse:SAMPLE: GSM1539138
30-Mar-2026 18:52:10 DEBUG GEOparse - SAMPLE: GSM1539139
DEBUG:GEOparse:SAMPLE: GSM1539139
30-Mar-2026 18:52:10 DEBUG GEOparse - SAMPLE: GSM1539140
DEBUG:GEOparse:SAMPLE: GSM1539140
30-Mar-2026 18:52:10 DEBUG GEOparse - SAMPLE: GSM1539141
DEBUG:GEOparse:SAMPLE: GSM1539141
30-Mar-2026 18:52:10 DEBUG GEOparse - SAMPLE: GSM1539142
DEBUG:GEOparse:SAMPLE: GSM1539142
30-Mar-2026 18:52:10 DEBUG GEOparse - SAMPLE: GSM1539143
DEBUG:GEOparse:SAMPLE: GSM1539143
30-Mar-2026 18:52:10 DEBUG GEOparse - SAMPLE: GSM1539144
DEBUG:GEOparse:SAMPLE: GSM1539144
30-Mar-2026 18:52:10 DEBUG GEOparse - SAMPLE: GSM1539145
DEBUG:GEOparse:SAMPLE: GSM1539145
30-Mar-2026 18:52:10 DEBUG GEOparse - SAMPLE: GSM1539146
DEBUG:GEOparse:SAMPLE: GSM1539146
30-Mar-2026 18:52:10 DEBUG GEOparse - SAMPLE: GSM1539147
DEBUG:GEOparse:SAMPLE: GSM1539147
30-Mar-2026 18:52:10 DEBUG GEOparse - SAMPLE: GSM1539148
DEBUG:GEOparse:SAMPLE: GSM1539148
30-Mar-2026 18:52:10 DEBUG GEOparse - SAMPLE: GSM1539149
DEBUG:GEOparse:SAMPLE: GSM1539149
30-Mar-2026 18:52:10 DEBUG GEOparse - SAMPLE: GSM1539150
DEBUG:GEOparse:SAMPLE: GSM1539150
30-Mar-2026 18:52:11 DEBUG GEOparse - SAMPLE: GSM1539151
DEBUG:GEOparse:SAMPLE: GSM1539151
30-Mar-2026 18:52:11 DEBUG GEOparse - SAMPLE: GSM1539152
DEBUG:GEOparse:SAMPLE: GSM1539152
30-Mar-2026 18:52:11 DEBUG GEOparse - SAMPLE: GSM1539153
DEBUG:GEOparse:SAMPLE: GSM1539153
30-Mar-2026 18:52:11 DEBUG GEOparse - SAMPLE: GSM1539154
DEBUG:GEOparse:SAMPLE: GSM1539154
30-Mar-2026 18:52:11 DEBUG GEOparse - SAMPLE: GSM1539155
DEBUG:GEOparse:SAMPLE: GSM1539155
30-Mar-2026 18:52:11 DEBUG GEOparse - SAMPLE: GSM1539156
DEBUG:GEOparse:SAMPLE: GSM1539156
30-Mar-2026 18:52:11 DEBUG GEOparse - SAMPLE: GSM1539157
DEBUG:GEOparse:SAMPLE: GSM1539157
30-Mar-2026 18:52:11 DEBUG GEOparse - SAMPLE: GSM1539158
DEBUG:GEOparse:SAMPLE: GSM1539158
30-Mar-2026 18:52:11 DEBUG GEOparse - SAMPLE: GSM1539159
DEBUG:GEOparse:SAMPLE: GSM1539159
30-Mar-2026 18:52:11 DEBUG GEOparse - SAMPLE: GSM1539160
DEBUG:GEOparse:SAMPLE: GSM1539160
30-Mar-2026 18:52:11 DEBUG GEOparse - SAMPLE: GSM1539161
DEBUG:GEOparse:SAMPLE: GSM1539161
30-Mar-2026 18:52:11 DEBUG GEOparse - SAMPLE: GSM1539162
DEBUG:GEOparse:SAMPLE: GSM1539162
30-Mar-2026 18:52:12 DEBUG GEOparse - SAMPLE: GSM1539163
DEBUG:GEOparse:SAMPLE: GSM1539163
30-Mar-2026 18:52:12 DEBUG GEOparse - SAMPLE: GSM1539164
DEBUG:GEOparse:SAMPLE: GSM1539164
30-Mar-2026 18:52:12 DEBUG GEOparse - SAMPLE: GSM1539165
DEBUG:GEOparse:SAMPLE: GSM1539165
30-Mar-2026 18:52:12 DEBUG GEOparse - SAMPLE: GSM1539166
DEBUG:GEOparse:SAMPLE: GSM1539166
30-Mar-2026 18:52:12 DEBUG GEOparse - SAMPLE: GSM1539167
DEBUG:GEOparse:SAMPLE: GSM1539167
30-Mar-2026 18:52:12 DEBUG GEOparse - SAMPLE: GSM1539168
DEBUG:GEOparse:SAMPLE: GSM1539168
30-Mar-2026 18:52:12 DEBUG GEOparse - SAMPLE: GSM1539169
DEBUG:GEOparse:SAMPLE: GSM1539169
30-Mar-2026 18:52:12 DEBUG GEOparse - SAMPLE: GSM1539170
DEBUG:GEOparse:SAMPLE: GSM1539170
30-Mar-2026 18:52:12 DEBUG GEOparse - SAMPLE: GSM1539171
DEBUG:GEOparse:SAMPLE: GSM1539171
30-Mar-2026 18:52:12 DEBUG GEOparse - SAMPLE: GSM1539172
DEBUG:GEOparse:SAMPLE: GSM1539172
30-Mar-2026 18:52:12 DEBUG GEOparse - SAMPLE: GSM1539173
DEBUG:GEOparse:SAMPLE: GSM1539173
30-Mar-2026 18:52:12 DEBUG GEOparse - SAMPLE: GSM1539174
DEBUG:GEOparse:SAMPLE: GSM1539174
30-Mar-2026 18:52:13 DEBUG GEOparse - SAMPLE: GSM1539175
DEBUG:GEOparse:SAMPLE: GSM1539175
30-Mar-2026 18:52:13 DEBUG GEOparse - SAMPLE: GSM1539176
DEBUG:GEOparse:SAMPLE: GSM1539176
30-Mar-2026 18:52:13 DEBUG GEOparse - SAMPLE: GSM1539177
DEBUG:GEOparse:SAMPLE: GSM1539177
30-Mar-2026 18:52:13 DEBUG GEOparse - SAMPLE: GSM1539178
DEBUG:GEOparse:SAMPLE: GSM1539178
30-Mar-2026 18:52:13 DEBUG GEOparse - SAMPLE: GSM1539179
DEBUG:GEOparse:SAMPLE: GSM1539179
30-Mar-2026 18:52:13 DEBUG GEOparse - SAMPLE: GSM1539180
DEBUG:GEOparse:SAMPLE: GSM1539180
30-Mar-2026 18:52:13 DEBUG GEOparse - SAMPLE: GSM1539181
DEBUG:GEOparse:SAMPLE: GSM1539181
30-Mar-2026 18:52:13 DEBUG GEOparse - SAMPLE: GSM1539182
DEBUG:GEOparse:SAMPLE: GSM1539182
30-Mar-2026 18:52:13 DEBUG GEOparse - SAMPLE: GSM1539183
DEBUG:GEOparse:SAMPLE: GSM1539183
30-Mar-2026 18:52:13 DEBUG GEOparse - SAMPLE: GSM1539184
DEBUG:GEOparse:SAMPLE: GSM1539184
30-Mar-2026 18:52:13 DEBUG GEOparse - SAMPLE: GSM1539185
DEBUG:GEOparse:SAMPLE: GSM1539185
30-Mar-2026 18:52:13 DEBUG GEOparse - SAMPLE: GSM1539186
DEBUG:GEOparse:SAMPLE: GSM1539186
30-Mar-2026 18:52:13 DEBUG GEOparse - SAMPLE: GSM1539187
DEBUG:GEOparse:SAMPLE: GSM1539187
30-Mar-2026 18:52:14 DEBUG GEOparse - SAMPLE: GSM1539188
DEBUG:GEOparse:SAMPLE: GSM1539188
30-Mar-2026 18:52:14 DEBUG GEOparse - SAMPLE: GSM1539189
DEBUG:GEOparse:SAMPLE: GSM1539189
30-Mar-2026 18:52:14 DEBUG GEOparse - SAMPLE: GSM1539190
DEBUG:GEOparse:SAMPLE: GSM1539190
30-Mar-2026 18:52:14 DEBUG GEOparse - SAMPLE: GSM1539191
DEBUG:GEOparse:SAMPLE: GSM1539191
30-Mar-2026 18:52:14 DEBUG GEOparse - SAMPLE: GSM1539192
DEBUG:GEOparse:SAMPLE: GSM1539192
30-Mar-2026 18:52:14 DEBUG GEOparse - SAMPLE: GSM1539193
DEBUG:GEOparse:SAMPLE: GSM1539193
30-Mar-2026 18:52:14 DEBUG GEOparse - SAMPLE: GSM1539194
DEBUG:GEOparse:SAMPLE: GSM1539194
30-Mar-2026 18:52:14 DEBUG GEOparse - SAMPLE: GSM1539195
DEBUG:GEOparse:SAMPLE: GSM1539195
30-Mar-2026 18:52:14 DEBUG GEOparse - SAMPLE: GSM1539196
DEBUG:GEOparse:SAMPLE: GSM1539196
30-Mar-2026 18:52:14 DEBUG GEOparse - SAMPLE: GSM1539197
DEBUG:GEOparse:SAMPLE: GSM1539197
30-Mar-2026 18:52:14 DEBUG GEOparse - SAMPLE: GSM1539198
DEBUG:GEOparse:SAMPLE: GSM1539198
30-Mar-2026 18:52:14 DEBUG GEOparse - SAMPLE: GSM1539199
DEBUG:GEOparse:SAMPLE: GSM1539199
30-Mar-2026 18:52:15 DEBUG GEOparse - SAMPLE: GSM1539200
DEBUG:GEOparse:SAMPLE: GSM1539200
30-Mar-2026 18:52:15 DEBUG GEOparse - SAMPLE: GSM1539201
DEBUG:GEOparse:SAMPLE: GSM1539201
30-Mar-2026 18:52:15 DEBUG GEOparse - SAMPLE: GSM1539202
DEBUG:GEOparse:SAMPLE: GSM1539202
30-Mar-2026 18:52:15 DEBUG GEOparse - SAMPLE: GSM1539203
DEBUG:GEOparse:SAMPLE: GSM1539203
30-Mar-2026 18:52:15 DEBUG GEOparse - SAMPLE: GSM1539204
DEBUG:GEOparse:SAMPLE: GSM1539204
30-Mar-2026 18:52:15 DEBUG GEOparse - SAMPLE: GSM1539205
DEBUG:GEOparse:SAMPLE: GSM1539205
30-Mar-2026 18:52:15 DEBUG GEOparse - SAMPLE: GSM1539206
DEBUG:GEOparse:SAMPLE: GSM1539206
30-Mar-2026 18:52:15 DEBUG GEOparse - SAMPLE: GSM1539207
DEBUG:GEOparse:SAMPLE: GSM1539207
30-Mar-2026 18:52:15 DEBUG GEOparse - SAMPLE: GSM1539208
DEBUG:GEOparse:SAMPLE: GSM1539208
30-Mar-2026 18:52:15 DEBUG GEOparse - SAMPLE: GSM1539209
DEBUG:GEOparse:SAMPLE: GSM1539209
30-Mar-2026 18:52:15 DEBUG GEOparse - SAMPLE: GSM1539210
DEBUG:GEOparse:SAMPLE: GSM1539210
30-Mar-2026 18:52:15 DEBUG GEOparse - SAMPLE: GSM1539211
DEBUG:GEOparse:SAMPLE: GSM1539211
30-Mar-2026 18:52:15 DEBUG GEOparse - SAMPLE: GSM1539212
DEBUG:GEOparse:SAMPLE: GSM1539212
30-Mar-2026 18:52:16 DEBUG GEOparse - SAMPLE: GSM1539213
DEBUG:GEOparse:SAMPLE: GSM1539213
30-Mar-2026 18:52:16 DEBUG GEOparse - SAMPLE: GSM1539214
DEBUG:GEOparse:SAMPLE: GSM1539214
30-Mar-2026 18:52:16 DEBUG GEOparse - SAMPLE: GSM1539215
DEBUG:GEOparse:SAMPLE: GSM1539215
30-Mar-2026 18:52:16 DEBUG GEOparse - SAMPLE: GSM1539216
DEBUG:GEOparse:SAMPLE: GSM1539216
30-Mar-2026 18:52:16 DEBUG GEOparse - SAMPLE: GSM1539217
DEBUG:GEOparse:SAMPLE: GSM1539217
30-Mar-2026 18:52:16 DEBUG GEOparse - SAMPLE: GSM1539218
DEBUG:GEOparse:SAMPLE: GSM1539218
30-Mar-2026 18:52:16 DEBUG GEOparse - SAMPLE: GSM1539219
DEBUG:GEOparse:SAMPLE: GSM1539219
30-Mar-2026 18:52:16 DEBUG GEOparse - SAMPLE: GSM1539220
DEBUG:GEOparse:SAMPLE: GSM1539220
30-Mar-2026 18:52:16 DEBUG GEOparse - SAMPLE: GSM1539221
DEBUG:GEOparse:SAMPLE: GSM1539221
30-Mar-2026 18:52:16 DEBUG GEOparse - SAMPLE: GSM1539222
DEBUG:GEOparse:SAMPLE: GSM1539222
30-Mar-2026 18:52:16 DEBUG GEOparse - SAMPLE: GSM1539223
DEBUG:GEOparse:SAMPLE: GSM1539223
30-Mar-2026 18:52:16 DEBUG GEOparse - SAMPLE: GSM1539224
DEBUG:GEOparse:SAMPLE: GSM1539224
30-Mar-2026 18:52:17 DEBUG GEOparse - SAMPLE: GSM1539225
DEBUG:GEOparse:SAMPLE: GSM1539225
30-Mar-2026 18:52:17 DEBUG GEOparse - SAMPLE: GSM1539226
DEBUG:GEOparse:SAMPLE: GSM1539226
30-Mar-2026 18:52:17 DEBUG GEOparse - SAMPLE: GSM1539227
DEBUG:GEOparse:SAMPLE: GSM1539227
30-Mar-2026 18:52:17 DEBUG GEOparse - SAMPLE: GSM1539228
DEBUG:GEOparse:SAMPLE: GSM1539228
30-Mar-2026 18:52:17 DEBUG GEOparse - SAMPLE: GSM1539229
DEBUG:GEOparse:SAMPLE: GSM1539229
30-Mar-2026 18:52:17 DEBUG GEOparse - SAMPLE: GSM1539230
DEBUG:GEOparse:SAMPLE: GSM1539230
30-Mar-2026 18:52:17 DEBUG GEOparse - SAMPLE: GSM1539231
DEBUG:GEOparse:SAMPLE: GSM1539231
30-Mar-2026 18:52:17 DEBUG GEOparse - SAMPLE: GSM1539232
DEBUG:GEOparse:SAMPLE: GSM1539232
30-Mar-2026 18:52:17 DEBUG GEOparse - SAMPLE: GSM1539233
DEBUG:GEOparse:SAMPLE: GSM1539233
30-Mar-2026 18:52:17 DEBUG GEOparse - SAMPLE: GSM1539234
DEBUG:GEOparse:SAMPLE: GSM1539234
30-Mar-2026 18:52:17 DEBUG GEOparse - SAMPLE: GSM1539235
DEBUG:GEOparse:SAMPLE: GSM1539235
30-Mar-2026 18:52:17 DEBUG GEOparse - SAMPLE: GSM1539236
DEBUG:GEOparse:SAMPLE: GSM1539236
30-Mar-2026 18:52:18 DEBUG GEOparse - SAMPLE: GSM1539237
DEBUG:GEOparse:SAMPLE: GSM1539237
30-Mar-2026 18:52:18 DEBUG GEOparse - SAMPLE: GSM1539238
DEBUG:GEOparse:SAMPLE: GSM1539238
30-Mar-2026 18:52:18 DEBUG GEOparse - SAMPLE: GSM1539239
DEBUG:GEOparse:SAMPLE: GSM1539239
30-Mar-2026 18:52:18 DEBUG GEOparse - SAMPLE: GSM1539240
DEBUG:GEOparse:SAMPLE: GSM1539240
30-Mar-2026 18:52:18 DEBUG GEOparse - SAMPLE: GSM1539241
DEBUG:GEOparse:SAMPLE: GSM1539241
30-Mar-2026 18:52:18 DEBUG GEOparse - SAMPLE: GSM1539242
DEBUG:GEOparse:SAMPLE: GSM1539242
30-Mar-2026 18:52:18 DEBUG GEOparse - SAMPLE: GSM1539243
DEBUG:GEOparse:SAMPLE: GSM1539243
30-Mar-2026 18:52:18 DEBUG GEOparse - SAMPLE: GSM1539244
DEBUG:GEOparse:SAMPLE: GSM1539244
30-Mar-2026 18:52:18 DEBUG GEOparse - SAMPLE: GSM1539245
DEBUG:GEOparse:SAMPLE: GSM1539245
30-Mar-2026 18:52:18 DEBUG GEOparse - SAMPLE: GSM1539246
DEBUG:GEOparse:SAMPLE: GSM1539246
30-Mar-2026 18:52:18 DEBUG GEOparse - SAMPLE: GSM1539247
DEBUG:GEOparse:SAMPLE: GSM1539247
30-Mar-2026 18:52:18 DEBUG GEOparse - SAMPLE: GSM1539248
DEBUG:GEOparse:SAMPLE: GSM1539248
30-Mar-2026 18:52:18 DEBUG GEOparse - SAMPLE: GSM1539249
DEBUG:GEOparse:SAMPLE: GSM1539249
30-Mar-2026 18:52:19 DEBUG GEOparse - SAMPLE: GSM1539250
DEBUG:GEOparse:SAMPLE: GSM1539250
30-Mar-2026 18:52:19 DEBUG GEOparse - SAMPLE: GSM1539251
DEBUG:GEOparse:SAMPLE: GSM1539251
30-Mar-2026 18:52:19 DEBUG GEOparse - SAMPLE: GSM1539252
DEBUG:GEOparse:SAMPLE: GSM1539252
30-Mar-2026 18:52:19 DEBUG GEOparse - SAMPLE: GSM1539253
DEBUG:GEOparse:SAMPLE: GSM1539253
30-Mar-2026 18:52:19 DEBUG GEOparse - SAMPLE: GSM1539254
DEBUG:GEOparse:SAMPLE: GSM1539254
30-Mar-2026 18:52:19 DEBUG GEOparse - SAMPLE: GSM1539255
DEBUG:GEOparse:SAMPLE: GSM1539255
30-Mar-2026 18:52:19 DEBUG GEOparse - SAMPLE: GSM1539256
DEBUG:GEOparse:SAMPLE: GSM1539256
30-Mar-2026 18:52:20 DEBUG GEOparse - SAMPLE: GSM1539257
DEBUG:GEOparse:SAMPLE: GSM1539257
30-Mar-2026 18:52:20 DEBUG GEOparse - SAMPLE: GSM1539258
DEBUG:GEOparse:SAMPLE: GSM1539258
30-Mar-2026 18:52:20 DEBUG GEOparse - SAMPLE: GSM1539259
DEBUG:GEOparse:SAMPLE: GSM1539259
30-Mar-2026 18:52:20 DEBUG GEOparse - SAMPLE: GSM1539260
DEBUG:GEOparse:SAMPLE: GSM1539260
30-Mar-2026 18:52:20 DEBUG GEOparse - SAMPLE: GSM1539261
DEBUG:GEOparse:SAMPLE: GSM1539261
30-Mar-2026 18:52:20 DEBUG GEOparse - SAMPLE: GSM1539262
DEBUG:GEOparse:SAMPLE: GSM1539262
30-Mar-2026 18:52:20 DEBUG GEOparse - SAMPLE: GSM1539263
DEBUG:GEOparse:SAMPLE: GSM1539263
30-Mar-2026 18:52:21 DEBUG GEOparse - SAMPLE: GSM1539264
DEBUG:GEOparse:SAMPLE: GSM1539264
30-Mar-2026 18:52:21 DEBUG GEOparse - SAMPLE: GSM1539265
DEBUG:GEOparse:SAMPLE: GSM1539265
30-Mar-2026 18:52:21 DEBUG GEOparse - SAMPLE: GSM1539266
DEBUG:GEOparse:SAMPLE: GSM1539266
30-Mar-2026 18:52:21 DEBUG GEOparse - SAMPLE: GSM1539267
DEBUG:GEOparse:SAMPLE: GSM1539267
30-Mar-2026 18:52:21 DEBUG GEOparse - SAMPLE: GSM1539268
DEBUG:GEOparse:SAMPLE: GSM1539268
30-Mar-2026 18:52:21 DEBUG GEOparse - SAMPLE: GSM1539269
DEBUG:GEOparse:SAMPLE: GSM1539269
30-Mar-2026 18:52:21 DEBUG GEOparse - SAMPLE: GSM1539270
DEBUG:GEOparse:SAMPLE: GSM1539270
30-Mar-2026 18:52:21 DEBUG GEOparse - SAMPLE: GSM1539271
DEBUG:GEOparse:SAMPLE: GSM1539271
30-Mar-2026 18:52:22 DEBUG GEOparse - SAMPLE: GSM1539272
DEBUG:GEOparse:SAMPLE: GSM1539272
30-Mar-2026 18:52:22 DEBUG GEOparse - SAMPLE: GSM1539273
DEBUG:GEOparse:SAMPLE: GSM1539273
30-Mar-2026 18:52:22 DEBUG GEOparse - SAMPLE: GSM1539274
DEBUG:GEOparse:SAMPLE: GSM1539274
30-Mar-2026 18:52:22 DEBUG GEOparse - SAMPLE: GSM1539275
DEBUG:GEOparse:SAMPLE: GSM1539275
30-Mar-2026 18:52:22 DEBUG GEOparse - SAMPLE: GSM1539276
DEBUG:GEOparse:SAMPLE: GSM1539276
30-Mar-2026 18:52:22 DEBUG GEOparse - SAMPLE: GSM1539277
DEBUG:GEOparse:SAMPLE: GSM1539277
30-Mar-2026 18:52:22 DEBUG GEOparse - SAMPLE: GSM1539278
DEBUG:GEOparse:SAMPLE: GSM1539278
30-Mar-2026 18:52:22 DEBUG GEOparse - SAMPLE: GSM1539279
DEBUG:GEOparse:SAMPLE: GSM1539279
30-Mar-2026 18:52:22 DEBUG GEOparse - SAMPLE: GSM1539280
DEBUG:GEOparse:SAMPLE: GSM1539280
30-Mar-2026 18:52:22 DEBUG GEOparse - SAMPLE: GSM1539281
DEBUG:GEOparse:SAMPLE: GSM1539281
30-Mar-2026 18:52:22 DEBUG GEOparse - SAMPLE: GSM1539282
DEBUG:GEOparse:SAMPLE: GSM1539282
30-Mar-2026 18:52:22 DEBUG GEOparse - SAMPLE: GSM1539283
DEBUG:GEOparse:SAMPLE: GSM1539283

In [4]:
print(gse)

<SERIES: GSE63060 - 329 SAMPLES, 1 d(s)>

In [5]:
# Extract expression data
samples = gse.gsms

data_list = []

for sample in samples.values():
    df = sample.table
    df = df[['ID_REF', 'VALUE']]
    df.columns = ['Gene', sample.name]
    data_list.append(df.set_index('Gene'))

expression_data = pd.concat(data_list, axis=1)

expression_data.head()

,GSM1539080,GSM1539081,GSM1539082,GSM1539083,GSM1539084,GSM1539085,GSM1539086,GSM1539087,GSM1539088,GSM1539089,...,GSM1539399,GSM1539400,GSM1539401,GSM1539402,GSM1539403,GSM1539404,GSM1539405,GSM1539406,GSM1539407,GSM1539408
Gene,,,,,,,,,,,,,,,,,,,,,
ILMN_2055271,7.600951,7.672496,7.538046,7.577860,7.678150,7.821754,7.538325,7.595028,7.617149,7.893230,...,7.577844,7.657990,7.702664,7.549431,7.424009,7.563977,7.606099,7.545535,7.567928,7.567190
ILMN_2383229,7.401991,7.414577,7.406980,7.455003,7.354241,7.487114,7.473277,7.414765,7.369689,7.425769,...,7.420044,7.327676,7.395640,7.455264,7.437403,7.296285,7.476446,7.365189,7.385004,7.411265
ILMN_1806310,7.650042,7.469146,7.478494,7.486963,7.446429,7.576292,7.408330,7.554633,7.430346,7.568055,...,7.648986,7.528787,7.527087,7.393601,7.511023,7.447771,7.507259,7.411622,7.456276,7.646164
ILMN_1779670,7.439318,7.505310,7.542144,7.567281,7.450938,7.664372,7.461290,7.591936,7.413166,7.438316,...,7.505358,7.490749,7.426290,7.428289,7.449399,7.499828,7.557032,7.497207,7.582703,7.498368
ILMN_2321282,7.538710,7.687544,7.602953,7.657317,7.615673,7.603043,7.537349,7.661408,7.624915,7.431161,...,7.693395,7.560890,7.411534,7.397306,7.544783,7.556252,7.575734,7.539473,7.578211,7.541192

In [6]:
expression_data.shape

(38323, 329)

In [7]:
expression_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 38323 entries, ILMN_2055271 to ILMN_2137536
Columns: 329 entries, GSM1539080 to GSM1539408
dtypes: float64(329)
memory usage: 96.5+ MB

In [8]:
# Extract sample information
metadata = []

for gsm_name, gsm in gse.gsms.items():
    metadata.append({
        "sample": gsm_name,
        "title": gsm.metadata.get("title", [""])[0],
        "source": gsm.metadata.get("source_name_ch1", [""])[0]
    })

metadata_df = pd.DataFrame(metadata)

metadata_df.head()

       sample         title source
0  GSM1539080  4856050008_I  Blood
1  GSM1539081  4856050047_D  Blood
2  GSM1539082  4856076009_D  Blood
3  GSM1539083  4856076040_F  Blood
4  GSM1539084  4856076002_E  Blood

In [9]:
metadata_df.shape

(329, 3)

In [10]:
metadata_df['source'].value_counts()

source
Blood    329
Name: count, dtype: int64

In [11]:
metadata_df.head(10)

       sample         title source
0  GSM1539080  4856050008_I  Blood
1  GSM1539081  4856050047_D  Blood
2  GSM1539082  4856076009_D  Blood
3  GSM1539083  4856076040_F  Blood
4  GSM1539084  4856076002_E  Blood
5  GSM1539085  4856076041_H  Blood
6  GSM1539086  4856076040_G  Blood
7  GSM1539087  4856076023_G  Blood
8  GSM1539088  4856076040_C  Blood
9  GSM1539089  4856050047_B  Blood

In [12]:
# Check characteristics field
for gsm_name, gsm in list(gse.gsms.items())[:5]:
    print(gsm.metadata.get("characteristics_ch1"))
    print("-----")

['status: MCI', 'ethnicity: Western European', 'age: 65', 'gender: Female', 'included in case -control study: yes', 'tissue: blood']
-----
['status: MCI', 'ethnicity: Other Caucasian', 'age: 66', 'gender: Female', 'included in case -control study: yes', 'tissue: blood']
-----
['status: MCI', 'ethnicity: Western European', 'age: 67', 'gender: Female', 'included in case -control study: yes', 'tissue: blood']
-----
['status: MCI', 'ethnicity: Unknown', 'age: 67', 'gender: Female', 'included in case -control study: yes', 'tissue: blood']
-----
['status: MCI', 'ethnicity: Western European', 'age: 67', 'gender: Female', 'included in case -control study: yes', 'tissue: blood']
-----

In [13]:
metadata = []

for gsm_name, gsm in gse.gsms.items():
    characteristics = gsm.metadata.get("characteristics_ch1", [])

    status = None
    for item in characteristics:
        if "status" in item:
            status = item.split(": ")[1]

    metadata.append({
        "sample": gsm_name,
        "status": status
    })

metadata_df = pd.DataFrame(metadata)

metadata_df.head()

       sample status
0  GSM1539080    MCI
1  GSM1539081    MCI
2  GSM1539082    MCI
3  GSM1539083    MCI
4  GSM1539084    MCI

In [14]:
metadata_df['status'].value_counts()

status
AD     145
CTL    104
MCI     80
Name: count, dtype: int64

Alzheimer vs Healthy

In [15]:
# Keep only AD and Control
filtered_metadata = metadata_df[
    metadata_df['status'].isin(['AD', 'CTL'])
]

filtered_metadata.shape

(249, 2)

In [16]:
# Match samples between expression data and metadata
selected_samples = filtered_metadata['sample'].values

filtered_expression = expression_data[selected_samples]

filtered_expression.shape

(38323, 249)

In [17]:
labels = filtered_metadata.set_index('sample').loc[selected_samples]['status']
labels = labels.map({'AD':1, 'CTL':0})

labels.head()

sample
GSM1539119    0
GSM1539120    0
GSM1539121    0
GSM1539122    0
GSM1539123    0
Name: status, dtype: int64

In [18]:
labels.value_counts()

status
1    145
0    104
Name: count, dtype: int64